### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by Lrcezimbra** [silvinho485/MyAnimeList#1]
The project doesn't have a license, it would be interesting to add one.

Without a license we can just view and fork the code, but can't use or modify it.

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

https://choosealicense.com/no-permission/

I usually use GPL or MIT, maybe is a good choice.
You can read more about licenses in https://choosealicense.com/.

**Comment by silvinho485** [comment]
![download](https://user-images.githubusercontent.com/16711930/36752140-ee42b114-1be0-11e8-9274-591ac6faad5b.jpeg)
